### ISSUE TITLE
Any update for support 3D Secure V2?

### ISSUE THREAD

**Issue by mkt-van** [cardinity/cardinity-sdk-php#13]
Hello, just want to ask when could we expect the update that support 3D Secure V2? We're (in the company) currently being required to update all our payment services. 
We we're able to update our [Java](https://github.com/cardinity/cardinity-sdk-java) as you guys already provided the update. Thank you for that! Hopefully PHP-SDK too real soon! Thank you

**Comment by SarunasCard** [comment]
Hello @mkt-van, PHP SDK release of version 3.0.0 is updated to support 3D Secure V2.

**Comment by mkt-van** [comment]
Thank you @SarunasCard for the update.
