### ISSUE TITLE
Upgrade GuzzleHttp

### ISSUE THREAD

**Issue by adam-boduch** [cardinity/cardinity-sdk-php#3]
Cardinity SDK requires guzzle 5.x although current version is 6.x.  I've been using version 6.x because other packages require that specific version. I can't install cardinity-sdk-php because of composer's conflict between those two versions.

**Comment by laimonasprei** [comment]
The same issue

**Comment by davfer** [comment]
Same

**Comment by eivydas** [comment]
Develop branch was updated with newest packages, stable version should be released in the upcoming weeks.
