### ISSUE TITLE
401 Unauthorized Issue

### ISSUE THREAD

**Issue by gcanwdn** [cardinity/cardinity-sdk-php#35]
I got cardinity-sdk-php. After I take Consumer Key and Consumer Secret from account. 

I wanted to try Get All Payments.  I am trying like this ;

use Cardinity\Client;
use Cardinity\Method\Payment;

$client = Client::create([
    'consumerKey' => 'my consumer key',
    'consumerSecret' => 'my consumer secret',
]);

$method = new Payment\GetAll();
$result = $client->call($method);
/** @type Cardinity\Method\Payment\Payment */
$payment = $result[0];

But response ; 

Fatal error: Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://api.cardinity.com/v1/payments?limit=10` resulted in a `401 Unauthorized` response: { "type": "https://developers.cardinity.com/api/v1/#401", "title": "Unauthorized", "status": 401, "detai (truncated...) in ../vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113

What is mean it ?

**Comment by MartynasS** [comment]
Hello,
Seems like the issue is with the key. Could you double check if it is entered correctly?
As for PHP SDK, there are more methods to get more specific error message: https://developers.cardinity.com/api/v1/?php#error-codes

**Comment by gcanwdn** [comment]
This issue something happened. Now error like this.

Cardinity\Method\Error Object
(
    [type:Cardinity\Method\Error:private] => https://developers.cardinity.com/api/v1/#401
    [title:Cardinity\Method\Error:private] => Unauthorized
    [status:Cardinity\Method\Error:private] => 401
    [detail:Cardinity\Method\Error:private] => Expired timestamp.
    [errors:Cardinity\Method\Error:private] => Array
        (
        )

)

**Comment by MartynasS** [comment]
Hello,

Expired timestamp usually means, that the server time is invalid.

**Comment by gcanwdn** [comment]
Hello thanks for your answer.

 I want to ask what timezone should be ?

**Comment by MartynasS** [comment]
UTC is default one. There is a command which updates server time, try using it. Because if there are even few minutes off, it throws an error.

**Comment by gcanwdn** [comment]
Is this command in the documentation?

**Comment by MartynasS** [comment]
The command date_default_timezone_set('*/*')
