### ISSUE TITLE
Amount should be positive value in 0.00 format as well as The value is not a valid float. Error

### ISSUE THREAD

**Issue by incontroincontri** [cardinity/cardinity-sdk-php#36]
Hi,
when creating the payment with `\Payment\Create($some_data = []);` i get this two Exception Errors each time i try to fix one of it

```
Cardinity\Exception\ValidationFailed
invalid amount: amount should be positive value in 0.00 format.

Cardinity\Exception\InvalidAttributeValue
[amount] The value "00.00" is not a valid float. 

```

Assuming we have an amount of **50** Euro

if i set the amount to be float, so **50** i get error from `ValidationFailed` Exception
if i set the amount in the required format 0.00 so **50.00** i get error from `InvalidAttributeValue` Exception

I'm using PHP 7.4 on Centos 7 with the latest Cardinity SDK

The only way to circumvent this error without touching the code is by using the `callNoValidate` instead of `call` method.

**Comment by MartynasS** [comment]
Hello, formatting is not right.
You can check an example on our Github that covers all of it -
https://github.com/cardinity/cardinity-example-php/blob/master/app/controllers/CardinityController.php

Amount needs to be on floating data type but with 2 decimal places.
'amount' => (float)sprintf('%.2f', $_POST['order']['amount']),
