### ISSUE TITLE
Can anyone elaborate what should be in PARES_RECEIVED_FROM_ACS and in what format ? 

### ISSUE THREAD

**Issue by csoftcom** [cardinity/cardinity-sdk-php#37]
I am trying to Finalize pending payment and in the 3D Secure V2 Example Request it is very unclear what should be in the PARES_RECEIVED_FROM_ACS

   Can anyone clarify that ? 

  Here is the example script : 

<?php
use Cardinity\Client;
use Cardinity\Method\Payment;

$client = Client::create([
    'consumerKey' => 'YOUR_CONSUMER_KEY',
    'consumerSecret' => 'YOUR_CONSUMER_SECRET',
]);

$method = new Payment\Finalize($payment->getId(), 'PARES_RECEIVED_FROM_ACS');
/** @type Cardinity\Method\Payment\Payment */
$payment = $client->call($method);

/** @type Cardinity\Method\Payment\Payment */
$method = new Payment\Finalize(
    $payment->getId(), // payment object received from API call
    $auth->getCreq(), // payment object received from API call
    true // BOOL `true` to enable 3D secure V2 parameters
);
// again use same try ... catch block
try {
    $payment = $client->call($method);
}
// same catch blocks as in Payment\Create...

**Comment by garas** [comment]
You get it as `$_POST['cres']` in callback page.
