### ISSUE TITLE
curl returns error with verify because of missing CA certificates

### ISSUE THREAD

**Issue by snovak7** [cardinity/cardinity-sdk-php#4]
In case of missing ca-certificates package on an Ubuntu, curl doesn't have any available CA certificates, and fails with UnexpectedError, this takes a lot of time to find a problem, if curl returns error, it would be great to return ConfigurationError or SystemConfigurationError Exception.

**Comment by eivydas** [comment]
You should be able to get error message with `$exception->getPrevious()->getMessage()`
